services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
      RAILS_ENV: development

volumes:
  postgres_data:
  bundle_cache:
